[package]
name = "SuiMoveAdmin"
edition = "2024.beta"
published-at = "0xc42e20749aeb3df5a5fc3af0fc008ab7b17a7537aefda9291a8ed725ee95c024"

[addresses]
sui_move_admin = "0xc42e20749aeb3df5a5fc3af0fc008ab7b17a7537aefda9291a8ed725ee95c024"
